{{- if .Values.privateGPTInstance.enabled -}}
apiVersion: privategpt.eirl/v1alpha1
kind: PrivateGPTInstance
metadata:
  name: default
  annotations:
    helm.sh/hook: post-install,post-upgrade
spec:
  ollamaURL: {{ .Values.privateGPTInstance.ollamaURL }}
  image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
  domain: {{ .Values.privateGPTInstance.domain }}
{{- end }}
